version: 2

defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: vuejs/ci

jobs:
  build:
    <<: *defaults
    steps:
      # 同步代码
      - checkout
      # 从缓存中获取
      - restore_cache:
          keys: 
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            # 如果没有匹配的缓存则使用最新的缓存
            - v1-dependencies
      # 查看目录
      - run: pwd && ls -al

      - run: 
          name: Installing Dependencies
          command: yarn --frozen-lockfile
      
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # 创建打包文件
      - run: 
          name: build package
          command: yarn run build:prod
      # 查看目录
      - run: pwd && ls -al
      # 存储缓存文件
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace

  deploy:
    <<: *defaults
    # machine:
    #   timezone:
    #     Asia/Shanghai # 设置时区
    #   enabled: true
    steps:
      - attach_workspace:  #获取上级工作流
          at: ~/workspace 
      - run: pwd && ls -al
      - run: 
          name: Deploy Over SSH
          command: .circleci/deploy-master.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master