version: 2
jobs:
  build:
    working_directory: /tmp/workspace
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:lts-jessie
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
      - run: echo "=========================构建开始========================="
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys: 
            - v1-dependency-cache-{{ checksum "package-lock.json" }}
            - v1-dependency-cache-

      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  deploy:
    machine:
      timezone:
        Asia/Shanghai # 设置时区
      enabled: true
    working_directory: /tmp/workspace
    steps:
      - run: echo "=========================部署开始========================="
      - attach_workspace:
          at: /tmp/workspace
      - run: pwd && ls -al
      - run: 
          name: Deploy Over SSH
          command: ./circleci/deploy-master.sh
      - run: echo "=========================部署完毕========================="
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master